use crate::color::Rgba;

/// Named colors enum with 140+ web colors
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NamedColor {
    // Basic colors
    Black,
    White,
    Red,
    Green,
    Blue,
    Yellow,
    Cyan,
    Magenta,
    
    // Grays
    Gray,
    LightGray,
    DarkGray,
    Silver,
    DimGray,
    Gainsboro,
    WhiteSmoke,
    
    // Reds
    IndianRed,
    LightCoral,
    Salmon,
    DarkSalmon,
    LightSalmon,
    Crimson,
    FireBrick,
    DarkRed,
    
    // Pinks
    Pink,
    LightPink,
    HotPink,
    DeepPink,
    MediumVioletRed,
    PaleVioletRed,
    
    // Oranges
    LightSalmonOrange,
    Coral,
    Tomato,
    OrangeRed,
    DarkOrange,
    Orange,
    
    // Yellows
    Gold,
    YellowGreen,
    LawnGreen,
    Chartreuse,
    Lime,
    LimeGreen,
    PaleGreen,
    LightGreen,
    MediumSpringGreen,
    SpringGreen,
    MediumSeaGreen,
    SeaGreen,
    ForestGreen,
    DarkGreen,
    MediumAquamarine,
    DarkSeaGreen,
    LightSeaGreen,
    DarkCyan,
    Teal,
    
    // Blues
    Aqua,
    LightCyan,
    PaleTurquoise,
    Aquamarine,
    Turquoise,
    MediumTurquoise,
    DarkTurquoise,
    CadetBlue,
    SteelBlue,
    LightSteelBlue,
    PowderBlue,
    LightBlue,
    SkyBlue,
    LightSkyBlue,
    DeepSkyBlue,
    DodgerBlue,
    CornflowerBlue,
    MediumSlateBlue,
    RoyalBlue,
    MediumBlue,
    DarkBlue,
    Navy,
    MidnightBlue,
    
    // Purples
    Lavender,
    Thistle,
    Plum,
    Violet,
    Orchid,
    Fuchsia,
    MagentaMedium,
    MediumOrchid,
    MediumPurple,
    BlueViolet,
    DarkViolet,
    DarkOrchid,
    DarkMagenta,
    Purple,
    Indigo,
    DarkSlateBlue,
    SlateBlue,
    
    // Browns
    Cornsilk,
    BlanchedAlmond,
    Bisque,
    NavajoWhite,
    Wheat,
    BurlyWood,
    Tan,
    RosyBrown,
    SandyBrown,
    Goldenrod,
    DarkGoldenrod,
    Peru,
    Chocolate,
    SaddleBrown,
    Sienna,
    Brown,
    Maroon,
    
    // Extended colors
    AliceBlue,
    AntiqueWhite,
    AquamarineLight,
    Azure,
    Beige,
    BisqueLight,
    BlackOlive,
    BlanchedAlmondLight,
    BlueAlice,
    BlueCornflower,
    BlueDark,
    BlueLight,
    BlueMedium,
    BlueMidnight,
    BlueNavy,
    BluePowder,
    BlueRoyal,
    BlueSky,
    BlueSlate,
    BlueSteel,
    BlueVioletDark,
    BrownChocolate,
    BrownCoral,
    BrownFire,
    BrownPeru,
    BrownRosy,
    BrownSaddle,
    BrownSandy,
    BrownSienna,
    Burlywood,
    CadetBlueDark,
    ChartreuseDark,
    ChocolateDark,
    CoralLight,
    CornflowerBlueDark,
    CornsilkLight,
    CrimsonDark,
    CyanDark,
    CyanLight,
    DarkBlueNavy,
    DarkGoldenrodLight,
    DarkGreenForest,
    DarkGreenSea,
    DarkKhaki,
    DarkOliveGreen,
    DarkOrangeLight,
    DarkOrchidLight,
    DarkRedFire,
    DarkSalmonLight,
    DarkSeaGreenLight,
    DarkSlateGray,
    DarkTurquoiseLight,
    DarkVioletLight,
    DeepPinkLight,
    DeepSkyBlueLight,
    DimGrayLight,
    DodgerBlueLight,
    FireBrickDark,
    FloralWhite,
    ForestGreenDark,
    FuchsiaMedium,
    GainsboroLight,
    GhostWhite,
    GoldLight,
    GoldenrodDark,
    GoldenrodLight,
    GrayDark,
    GrayDim,
    GrayLight,
    GraySlate,
    GreenDark,
    GreenForest,
    GreenLime,
    GreenMedium,
    GreenMediumSea,
    GreenPale,
    GreenSea,
    GreenYellow,
    Honeydew,
    HotPinkLight,
    IndianRedDark,
    IndianRedLight,
    IndigoDark,
    Ivory,
    Khaki,
    KhakiDark,
    KhakiLight,
    LavenderBlush,
    LawnGreenDark,
    LemonChiffon,
    LightBlueAlice,
    LightBlueLight,
    LightBluePowder,
    LightBlueSky,
    LightBlueSteel,
    LightCoralDark,
    LightCyanDark,
    LightGoldenrodYellow,
    LightGrayDark,
    LightGreenDark,
    LightGreenPale,
    LightPinkDark,
    LightSalmonDark,
    LightSeaGreenDark,
    LightSkyBlueDark,
    LightSlateGray,
    LightSteelBlueDark,
    LightYellowDark,
    LimeGreenDark,
    Linen,
    MagentaDark,
    MaroonDark,
    MediumAquamarineDark,
    MediumBlueDark,
    MediumOrchidDark,
    MediumPurpleDark,
    MediumSeaGreenDark,
    MediumSlateBlueDark,
    MediumSpringGreenDark,
    MediumTurquoiseDark,
    MediumVioletRedDark,
    MidnightBlueDark,
    MintCream,
    MistyRose,
    Moccasin,
    NavajoWhiteDark,
    NavyDark,
    OldLace,
    Olive,
    OliveDrab,
    OliveDrabDark,
    OrangeDark,
    OrangeRedDark,
    OrchidDark,
    OrchidMedium,
    PaleGoldenrod,
    PaleGreenDark,
    PaleTurquoiseDark,
    PaleVioletRedDark,
    PapayaWhip,
    PeachPuff,
    PeruDark,
    PinkDark,
    PinkHot,
    PinkLight,
    PinkMedium,
    PlumDark,
    PowderBlueDark,
    PurpleDark,
    PurpleMedium,
    RedDark,
    RedIndian,
    RedLight,
    RosyBrownDark,
    RoyalBlueDark,
    SaddleBrownDark,
    SalmonDark,
    SalmonLight,
    SandyBrownDark,
    SeaGreenDark,
    SeaGreenMedium,
    SeaShell,
    SiennaDark,
    SkyBlueDark,
    SkyBlueLight,
    SlateBlueDark,
    SlateBlueMedium,
    SlateGray,
    SlateGrayDark,
    SlateGrayLight,
    Snow,
    SpringGreenDark,
    SpringGreenMedium,
    SteelBlueDark,
    SteelBlueLight,
    TanDark,
    TealDark,
    ThistleDark,
    TomatoDark,
    TurquoiseDark,
    TurquoiseMedium,
    VioletDark,
    WheatDark,
    WhiteDark,
    WhiteSmokeDark,
    YellowDark,
    YellowGreenDark,
}

impl NamedColor {
    /// Convert named color to RGBA
    pub fn to_rgba(&self) -> Rgba {
        match self {
            // Basic colors
            NamedColor::Black => Rgba::rgb(0, 0, 0),
            NamedColor::White => Rgba::rgb(255, 255, 255),
            NamedColor::Red => Rgba::rgb(255, 0, 0),
            NamedColor::Green => Rgba::rgb(0, 128, 0),
            NamedColor::Blue => Rgba::rgb(0, 0, 255),
            NamedColor::Yellow => Rgba::rgb(255, 255, 0),
            NamedColor::Cyan => Rgba::rgb(0, 255, 255),
            NamedColor::Magenta => Rgba::rgb(255, 0, 255),
            
            // Grays
            NamedColor::Gray => Rgba::rgb(128, 128, 128),
            NamedColor::LightGray => Rgba::rgb(211, 211, 211),
            NamedColor::DarkGray => Rgba::rgb(169, 169, 169),
            NamedColor::Silver => Rgba::rgb(192, 192, 192),
            NamedColor::DimGray => Rgba::rgb(105, 105, 105),
            NamedColor::Gainsboro => Rgba::rgb(220, 220, 220),
            NamedColor::WhiteSmoke => Rgba::rgb(245, 245, 245),
            
            // Reds
            NamedColor::IndianRed => Rgba::rgb(205, 92, 92),
            NamedColor::LightCoral => Rgba::rgb(240, 128, 128),
            NamedColor::Salmon => Rgba::rgb(250, 128, 114),
            NamedColor::DarkSalmon => Rgba::rgb(233, 150, 122),
            NamedColor::LightSalmon => Rgba::rgb(255, 160, 122),
            NamedColor::Crimson => Rgba::rgb(220, 20, 60),
            NamedColor::FireBrick => Rgba::rgb(178, 34, 34),
            NamedColor::DarkRed => Rgba::rgb(139, 0, 0),
            
            // Pinks
            NamedColor::Pink => Rgba::rgb(255, 192, 203),
            NamedColor::LightPink => Rgba::rgb(255, 182, 193),
            NamedColor::HotPink => Rgba::rgb(255, 105, 180),
            NamedColor::DeepPink => Rgba::rgb(255, 20, 147),
            NamedColor::MediumVioletRed => Rgba::rgb(199, 21, 133),
            NamedColor::PaleVioletRed => Rgba::rgb(219, 112, 147),
            
            // Oranges
            NamedColor::LightSalmonOrange => Rgba::rgb(255, 160, 122),
            NamedColor::Coral => Rgba::rgb(255, 127, 80),
            NamedColor::Tomato => Rgba::rgb(255, 99, 71),
            NamedColor::OrangeRed => Rgba::rgb(255, 69, 0),
            NamedColor::DarkOrange => Rgba::rgb(255, 140, 0),
            NamedColor::Orange => Rgba::rgb(255, 165, 0),
            
            // Yellows/Greens
            NamedColor::Gold => Rgba::rgb(255, 215, 0),
            NamedColor::YellowGreen => Rgba::rgb(154, 205, 50),
            NamedColor::LawnGreen => Rgba::rgb(124, 252, 0),
            NamedColor::Chartreuse => Rgba::rgb(127, 255, 0),
            NamedColor::Lime => Rgba::rgb(0, 255, 0),
            NamedColor::LimeGreen => Rgba::rgb(50, 205, 50),
            NamedColor::PaleGreen => Rgba::rgb(152, 251, 152),
            NamedColor::LightGreen => Rgba::rgb(144, 238, 144),
            NamedColor::MediumSpringGreen => Rgba::rgb(0, 250, 154),
            NamedColor::SpringGreen => Rgba::rgb(0, 255, 127),
            NamedColor::MediumSeaGreen => Rgba::rgb(60, 179, 113),
            NamedColor::SeaGreen => Rgba::rgb(46, 139, 87),
            NamedColor::ForestGreen => Rgba::rgb(34, 139, 34),
            NamedColor::DarkGreen => Rgba::rgb(0, 128, 0),
            NamedColor::MediumAquamarine => Rgba::rgb(102, 205, 170),
            NamedColor::DarkSeaGreen => Rgba::rgb(143, 188, 143),
            NamedColor::LightSeaGreen => Rgba::rgb(32, 178, 170),
            NamedColor::DarkCyan => Rgba::rgb(0, 139, 139),
            NamedColor::Teal => Rgba::rgb(0, 128, 128),
            
            // Extended colors that appear in enum
            NamedColor::AquamarineLight => Rgba::rgb(127, 255, 212),
            NamedColor::BlueMedium => Rgba::rgb(0, 0, 205),
            NamedColor::GreenDark => Rgba::rgb(0, 100, 0),
            
            // Blues
            NamedColor::Aqua => Rgba::rgb(0, 255, 255),
            NamedColor::Cyan => Rgba::rgb(0, 255, 255),
            NamedColor::LightCyan => Rgba::rgb(224, 255, 255),
            NamedColor::PaleTurquoise => Rgba::rgb(175, 238, 238),
            NamedColor::Aquamarine => Rgba::rgb(127, 255, 212),
            NamedColor::Turquoise => Rgba::rgb(64, 224, 208),
            NamedColor::MediumTurquoise => Rgba::rgb(72, 209, 204),
            NamedColor::DarkTurquoise => Rgba::rgb(0, 206, 209),
            NamedColor::CadetBlue => Rgba::rgb(95, 158, 160),
            NamedColor::SteelBlue => Rgba::rgb(70, 130, 180),
            NamedColor::LightSteelBlue => Rgba::rgb(176, 196, 222),
            NamedColor::PowderBlue => Rgba::rgb(176, 224, 230),
            NamedColor::LightBlue => Rgba::rgb(173, 216, 230),
            NamedColor::SkyBlue => Rgba::rgb(135, 206, 235),
            NamedColor::LightSkyBlue => Rgba::rgb(135, 206, 250),
            NamedColor::DeepSkyBlue => Rgba::rgb(0, 191, 255),
            NamedColor::DodgerBlue => Rgba::rgb(30, 144, 255),
            NamedColor::CornflowerBlue => Rgba::rgb(100, 149, 237),
            NamedColor::MediumSlateBlue => Rgba::rgb(123, 104, 238),
            NamedColor::RoyalBlue => Rgba::rgb(65, 105, 225),
            NamedColor::MediumBlue => Rgba::rgb(0, 0, 205),
            NamedColor::DarkBlue => Rgba::rgb(0, 0, 139),
            NamedColor::Navy => Rgba::rgb(0, 0, 128),
            NamedColor::MidnightBlue => Rgba::rgb(25, 25, 112),
            
            // Purples
            NamedColor::Lavender => Rgba::rgb(230, 230, 250),
            NamedColor::Thistle => Rgba::rgb(216, 191, 216),
            NamedColor::Plum => Rgba::rgb(221, 160, 221),
            NamedColor::Violet => Rgba::rgb(238, 130, 238),
            NamedColor::Orchid => Rgba::rgb(218, 112, 214),
            NamedColor::Fuchsia => Rgba::rgb(255, 0, 255),
            NamedColor::MagentaMedium => Rgba::rgb(186, 85, 211),
            NamedColor::MediumOrchid => Rgba::rgb(186, 85, 211),
            NamedColor::MediumPurple => Rgba::rgb(147, 112, 219),
            NamedColor::BlueViolet => Rgba::rgb(138, 43, 226),
            NamedColor::DarkViolet => Rgba::rgb(148, 0, 211),
            NamedColor::DarkOrchid => Rgba::rgb(153, 50, 204),
            NamedColor::DarkMagenta => Rgba::rgb(139, 0, 139),
            NamedColor::Purple => Rgba::rgb(128, 0, 128),
            NamedColor::Indigo => Rgba::rgb(75, 0, 130),
            NamedColor::DarkSlateBlue => Rgba::rgb(72, 61, 139),
            NamedColor::SlateBlue => Rgba::rgb(106, 90, 205),
            
            // Browns
            NamedColor::Cornsilk => Rgba::rgb(255, 248, 220),
            NamedColor::BlanchedAlmond => Rgba::rgb(255, 235, 205),
            NamedColor::Bisque => Rgba::rgb(255, 228, 196),
            NamedColor::NavajoWhite => Rgba::rgb(255, 222, 173),
            NamedColor::Wheat => Rgba::rgb(245, 222, 179),
            NamedColor::BurlyWood => Rgba::rgb(222, 184, 135),
            NamedColor::Tan => Rgba::rgb(210, 180, 140),
            NamedColor::RosyBrown => Rgba::rgb(188, 143, 143),
            NamedColor::SandyBrown => Rgba::rgb(244, 164, 96),
            NamedColor::Goldenrod => Rgba::rgb(218, 165, 32),
            NamedColor::DarkGoldenrod => Rgba::rgb(184, 134, 11),
            NamedColor::Peru => Rgba::rgb(205, 133, 63),
            NamedColor::Chocolate => Rgba::rgb(210, 105, 30),
            NamedColor::SaddleBrown => Rgba::rgb(139, 69, 19),
            NamedColor::Sienna => Rgba::rgb(160, 82, 45),
            NamedColor::Brown => Rgba::rgb(165, 42, 42),
            NamedColor::Maroon => Rgba::rgb(128, 0, 0),
            
            // Extended colors - placeholder for remaining colors
            NamedColor::LightSalmonOrange => Rgba::rgb(255, 160, 122),
            NamedColor::AliceBlue => Rgba::rgb(240, 248, 255),
            NamedColor::AntiqueWhite => Rgba::rgb(250, 235, 215),
            NamedColor::Azure => Rgba::rgb(240, 255, 255),
            NamedColor::Beige => Rgba::rgb(245, 245, 220),
            NamedColor::BisqueLight => Rgba::rgb(255, 228, 196),
            NamedColor::BlackOlive => Rgba::rgb(59, 60, 54),
            NamedColor::BlanchedAlmondLight => Rgba::rgb(255, 235, 205),
            NamedColor::BlueAlice => Rgba::rgb(240, 248, 255),
            NamedColor::BlueCornflower => Rgba::rgb(100, 149, 237),
            NamedColor::BlueDark => Rgba::rgb(0, 0, 139),
            NamedColor::BlueLight => Rgba::rgb(173, 216, 230),
            NamedColor::BlueMidnight => Rgba::rgb(25, 25, 112),
            NamedColor::BlueNavy => Rgba::rgb(0, 0, 128),
            NamedColor::BluePowder => Rgba::rgb(176, 224, 230),
            NamedColor::BlueRoyal => Rgba::rgb(65, 105, 225),
            NamedColor::BlueSky => Rgba::rgb(135, 206, 235),
            NamedColor::BlueSlate => Rgba::rgb(106, 90, 205),
            NamedColor::BlueSteel => Rgba::rgb(70, 130, 180),
            NamedColor::BlueVioletDark => Rgba::rgb(138, 43, 226),
            NamedColor::BrownChocolate => Rgba::rgb(210, 105, 30),
            NamedColor::BrownCoral => Rgba::rgb(255, 127, 80),
            NamedColor::BrownFire => Rgba::rgb(178, 34, 34),
            NamedColor::BrownPeru => Rgba::rgb(205, 133, 63),
            NamedColor::BrownRosy => Rgba::rgb(188, 143, 143),
            NamedColor::BrownSaddle => Rgba::rgb(139, 69, 19),
            NamedColor::BrownSandy => Rgba::rgb(244, 164, 96),
            NamedColor::BrownSienna => Rgba::rgb(160, 82, 45),
            NamedColor::Burlywood => Rgba::rgb(222, 184, 135),
            NamedColor::CadetBlueDark => Rgba::rgb(95, 158, 160),
            NamedColor::ChartreuseDark => Rgba::rgb(127, 255, 0),
            NamedColor::ChocolateDark => Rgba::rgb(210, 105, 30),
            NamedColor::CoralLight => Rgba::rgb(255, 127, 80),
            NamedColor::CornflowerBlueDark => Rgba::rgb(100, 149, 237),
            NamedColor::CornsilkLight => Rgba::rgb(255, 248, 220),
            NamedColor::CrimsonDark => Rgba::rgb(220, 20, 60),
            NamedColor::CyanDark => Rgba::rgb(0, 139, 139),
            NamedColor::CyanLight => Rgba::rgb(224, 255, 255),
            NamedColor::DarkBlueNavy => Rgba::rgb(0, 0, 128),
            NamedColor::DarkGoldenrodLight => Rgba::rgb(184, 134, 11),
            NamedColor::DarkGreenForest => Rgba::rgb(34, 139, 34),
            NamedColor::DarkGreenSea => Rgba::rgb(143, 188, 143),
            NamedColor::DarkKhaki => Rgba::rgb(189, 183, 107),
            NamedColor::DarkOliveGreen => Rgba::rgb(85, 107, 47),
            NamedColor::DarkOrangeLight => Rgba::rgb(255, 140, 0),
            NamedColor::DarkOrchidLight => Rgba::rgb(153, 50, 204),
            NamedColor::DarkRedFire => Rgba::rgb(178, 34, 34),
            NamedColor::DarkSalmonLight => Rgba::rgb(233, 150, 122),
            NamedColor::DarkSeaGreenLight => Rgba::rgb(143, 188, 143),
            NamedColor::DarkSlateGray => Rgba::rgb(47, 79, 79),
            NamedColor::DarkTurquoiseLight => Rgba::rgb(0, 206, 209),
            NamedColor::DarkVioletLight => Rgba::rgb(148, 0, 211),
            NamedColor::DeepPinkLight => Rgba::rgb(255, 20, 147),
            NamedColor::DeepSkyBlueLight => Rgba::rgb(0, 191, 255),
            NamedColor::DimGrayLight => Rgba::rgb(105, 105, 105),
            NamedColor::DodgerBlueLight => Rgba::rgb(30, 144, 255),
            NamedColor::FireBrickDark => Rgba::rgb(178, 34, 34),
            NamedColor::FloralWhite => Rgba::rgb(255, 250, 240),
            NamedColor::ForestGreenDark => Rgba::rgb(34, 139, 34),
            NamedColor::FuchsiaMedium => Rgba::rgb(255, 0, 255),
            NamedColor::GainsboroLight => Rgba::rgb(220, 220, 220),
            NamedColor::GhostWhite => Rgba::rgb(248, 248, 255),
            NamedColor::GoldLight => Rgba::rgb(255, 215, 0),
            NamedColor::GoldenrodDark => Rgba::rgb(218, 165, 32),
            NamedColor::GoldenrodLight => Rgba::rgb(218, 165, 32),
            NamedColor::GrayDark => Rgba::rgb(169, 169, 169),
            NamedColor::GrayDim => Rgba::rgb(105, 105, 105),
            NamedColor::GrayLight => Rgba::rgb(211, 211, 211),
            NamedColor::GraySlate => Rgba::rgb(112, 128, 144),
            NamedColor::GreenForest => Rgba::rgb(34, 139, 34),
            NamedColor::GreenLime => Rgba::rgb(0, 255, 0),
            NamedColor::GreenMedium => Rgba::rgb(0, 128, 0),
            NamedColor::GreenMediumSea => Rgba::rgb(60, 179, 113),
            NamedColor::GreenPale => Rgba::rgb(152, 251, 152),
            NamedColor::GreenSea => Rgba::rgb(46, 139, 87),
            NamedColor::GreenYellow => Rgba::rgb(173, 255, 47),
            NamedColor::Honeydew => Rgba::rgb(240, 255, 240),
            NamedColor::HotPinkLight => Rgba::rgb(255, 105, 180),
            NamedColor::IndianRedDark => Rgba::rgb(205, 92, 92),
            NamedColor::IndianRedLight => Rgba::rgb(205, 92, 92),
            NamedColor::IndigoDark => Rgba::rgb(75, 0, 130),
            NamedColor::Ivory => Rgba::rgb(255, 255, 240),
            NamedColor::Khaki => Rgba::rgb(240, 230, 140),
            NamedColor::KhakiDark => Rgba::rgb(189, 183, 107),
            NamedColor::KhakiLight => Rgba::rgb(240, 230, 140),
            NamedColor::LavenderBlush => Rgba::rgb(255, 240, 245),
            NamedColor::LawnGreenDark => Rgba::rgb(124, 252, 0),
            NamedColor::LemonChiffon => Rgba::rgb(255, 250, 205),
            NamedColor::LightBlueAlice => Rgba::rgb(240, 248, 255),
            NamedColor::LightBlueLight => Rgba::rgb(173, 216, 230),
            NamedColor::LightBluePowder => Rgba::rgb(176, 224, 230),
            NamedColor::LightBlueSky => Rgba::rgb(135, 206, 250),
            NamedColor::LightBlueSteel => Rgba::rgb(176, 196, 222),
            NamedColor::LightCoralDark => Rgba::rgb(240, 128, 128),
            NamedColor::LightCyanDark => Rgba::rgb(224, 255, 255),
            NamedColor::LightGoldenrodYellow => Rgba::rgb(250, 250, 210),
            NamedColor::LightGrayDark => Rgba::rgb(211, 211, 211),
            NamedColor::LightGreenDark => Rgba::rgb(144, 238, 144),
            NamedColor::LightGreenPale => Rgba::rgb(152, 251, 152),
            NamedColor::LightPinkDark => Rgba::rgb(255, 182, 193),
            NamedColor::LightSalmonDark => Rgba::rgb(255, 160, 122),
            NamedColor::LightSeaGreenDark => Rgba::rgb(32, 178, 170),
            NamedColor::LightSkyBlueDark => Rgba::rgb(135, 206, 250),
            NamedColor::LightSlateGray => Rgba::rgb(119, 136, 153),
            NamedColor::LightSteelBlueDark => Rgba::rgb(176, 196, 222),
            NamedColor::LightYellowDark => Rgba::rgb(255, 255, 224),
            NamedColor::LimeGreenDark => Rgba::rgb(50, 205, 50),
            NamedColor::Linen => Rgba::rgb(250, 240, 230),
            NamedColor::MagentaDark => Rgba::rgb(255, 0, 255),
            NamedColor::MaroonDark => Rgba::rgb(128, 0, 0),
            NamedColor::MediumAquamarineDark => Rgba::rgb(102, 205, 170),
            NamedColor::MediumBlueDark => Rgba::rgb(0, 0, 205),
            NamedColor::MediumOrchidDark => Rgba::rgb(186, 85, 211),
            NamedColor::MediumPurpleDark => Rgba::rgb(147, 112, 219),
            NamedColor::MediumSeaGreenDark => Rgba::rgb(60, 179, 113),
            NamedColor::MediumSlateBlueDark => Rgba::rgb(123, 104, 238),
            NamedColor::MediumSpringGreenDark => Rgba::rgb(0, 250, 154),
            NamedColor::MediumTurquoiseDark => Rgba::rgb(72, 209, 204),
            NamedColor::MediumVioletRedDark => Rgba::rgb(199, 21, 133),
            NamedColor::MidnightBlueDark => Rgba::rgb(25, 25, 112),
            NamedColor::MintCream => Rgba::rgb(245, 255, 250),
            NamedColor::MistyRose => Rgba::rgb(255, 228, 225),
            NamedColor::Moccasin => Rgba::rgb(255, 228, 181),
            NamedColor::NavajoWhiteDark => Rgba::rgb(255, 222, 173),
            NamedColor::NavyDark => Rgba::rgb(0, 0, 128),
            NamedColor::OldLace => Rgba::rgb(253, 245, 230),
            NamedColor::Olive => Rgba::rgb(128, 128, 0),
            NamedColor::OliveDrab => Rgba::rgb(107, 142, 35),
            NamedColor::OliveDrabDark => Rgba::rgb(107, 142, 35),
            NamedColor::OrangeDark => Rgba::rgb(255, 165, 0),
            NamedColor::OrangeRedDark => Rgba::rgb(255, 69, 0),
            NamedColor::OrchidDark => Rgba::rgb(218, 112, 214),
            NamedColor::OrchidMedium => Rgba::rgb(186, 85, 211),
            NamedColor::PaleGoldenrod => Rgba::rgb(238, 232, 170),
            NamedColor::PaleGreenDark => Rgba::rgb(152, 251, 152),
            NamedColor::PaleTurquoiseDark => Rgba::rgb(175, 238, 238),
            NamedColor::PaleVioletRedDark => Rgba::rgb(219, 112, 147),
            NamedColor::PapayaWhip => Rgba::rgb(255, 239, 213),
            NamedColor::PeachPuff => Rgba::rgb(255, 218, 185),
            NamedColor::PeruDark => Rgba::rgb(205, 133, 63),
            NamedColor::PinkDark => Rgba::rgb(255, 192, 203),
            NamedColor::PinkHot => Rgba::rgb(255, 105, 180),
            NamedColor::PinkLight => Rgba::rgb(255, 182, 193),
            NamedColor::PinkMedium => Rgba::rgb(255, 192, 203),
            NamedColor::PlumDark => Rgba::rgb(221, 160, 221),
            NamedColor::PowderBlueDark => Rgba::rgb(176, 224, 230),
            NamedColor::PurpleDark => Rgba::rgb(128, 0, 128),
            NamedColor::PurpleMedium => Rgba::rgb(147, 112, 219),
            NamedColor::RedDark => Rgba::rgb(255, 0, 0),
            NamedColor::RedIndian => Rgba::rgb(205, 92, 92),
            NamedColor::RedLight => Rgba::rgb(255, 0, 0),
            NamedColor::RosyBrownDark => Rgba::rgb(188, 143, 143),
            NamedColor::RoyalBlueDark => Rgba::rgb(65, 105, 225),
            NamedColor::SaddleBrownDark => Rgba::rgb(139, 69, 19),
            NamedColor::SalmonDark => Rgba::rgb(250, 128, 114),
            NamedColor::SalmonLight => Rgba::rgb(250, 128, 114),
            NamedColor::SandyBrownDark => Rgba::rgb(244, 164, 96),
            NamedColor::SeaGreenDark => Rgba::rgb(46, 139, 87),
            NamedColor::SeaGreenMedium => Rgba::rgb(60, 179, 113),
            NamedColor::SeaShell => Rgba::rgb(255, 245, 238),
            NamedColor::SiennaDark => Rgba::rgb(160, 82, 45),
            NamedColor::SkyBlueDark => Rgba::rgb(135, 206, 235),
            NamedColor::SkyBlueLight => Rgba::rgb(135, 206, 250),
            NamedColor::SlateBlueDark => Rgba::rgb(106, 90, 205),
            NamedColor::SlateBlueMedium => Rgba::rgb(123, 104, 238),
            NamedColor::SlateGray => Rgba::rgb(112, 128, 144),
            NamedColor::SlateGrayDark => Rgba::rgb(47, 79, 79),
            NamedColor::SlateGrayLight => Rgba::rgb(119, 136, 153),
            NamedColor::Snow => Rgba::rgb(255, 250, 250),
            NamedColor::SpringGreenDark => Rgba::rgb(0, 255, 127),
            NamedColor::SpringGreenMedium => Rgba::rgb(0, 250, 154),
            NamedColor::SteelBlueDark => Rgba::rgb(70, 130, 180),
            NamedColor::SteelBlueLight => Rgba::rgb(176, 196, 222),
            NamedColor::TanDark => Rgba::rgb(210, 180, 140),
            NamedColor::TealDark => Rgba::rgb(0, 128, 128),
            NamedColor::ThistleDark => Rgba::rgb(216, 191, 216),
            NamedColor::TomatoDark => Rgba::rgb(255, 99, 71),
            NamedColor::TurquoiseDark => Rgba::rgb(64, 224, 208),
            NamedColor::TurquoiseMedium => Rgba::rgb(72, 209, 204),
            NamedColor::VioletDark => Rgba::rgb(238, 130, 238),
            NamedColor::WheatDark => Rgba::rgb(245, 222, 179),
            NamedColor::WhiteDark => Rgba::rgb(255, 255, 255),
            NamedColor::WhiteSmokeDark => Rgba::rgb(245, 245, 245),
            NamedColor::YellowDark => Rgba::rgb(255, 255, 0),
            NamedColor::YellowGreenDark => Rgba::rgb(154, 205, 50),
        }
    }
}

